fslaborg/flips

Flips/Domain.fs
README.md

Filled out the domain for the Model domain to enable adding Constraints and Objectives

Fill out model domain

---

Flips.Console/Program.fs
Flips/Domain.fs
Flips/Extensions.fs
Flips/Flips.fsproj
Flips/Scratchpad.fsx
Flips/Solve.fs

Created the ConstraintBuilder computation expression and provided an example problem of how it is used

Constraint builder ce

---

Flips.Examples/Program.fs
Flips/Domain.fs
Flips/Flips.fsproj
Flips/Scratchpad.fsx
Flips/Solve.fs

* Change return type of the Decision.create functions to be Decision
* Added DecisionBuilder CE
Closing #39

Issue 39: Change composition rules for Decision

---

Flips.Examples/Program.fs
Flips/Flips.fsproj
Flips/Scratchpad.fsx
README.md

- Documented Domain Types
- Made it easier to get values back from Solution
- Added Computation Expression for creating Decisions
Close #39

Document domain

---

Flips.Tests/Gens.fs
Flips.Tests/Tests.fs
Flips/Domain.fs
Flips/Flips.fsproj

Added overloads for Decision and float

46 decision float interaction

---

Docs/index.html

Enable dark theme toggle

---

Flips/Domain.fs

Fix wrong binding in lambda expression.

Fix wrong binding

---

Flips.Examples/BinaryProgrammingExample/BinaryProgrammingExample.fs
Flips.Examples/CoffeeRoastingExample/CoffeeRoastingExample.fs
Flips.Examples/Flips.Examples.fsproj
Flips.Examples/FoodTruckConstraintBuilderExample/FoodTruckConstraintBuilderExample.fs
Flips.Examples/FoodTruckDecisionBuilder/FoodTruckDecisionBuilder.fs
Flips.Examples/FoodTruckExample/FoodTruckExample.fs
Flips.Examples/FoodTruckMapExample/FoodTruckMapExample.fs
Flips.Examples/FoodTruckUnitsOfMeasureExample/FoodTruckUnitsOfMeasureExample.fs
Flips.Examples/MapSlicingExample/MapSlicingExample.fs
Flips.Examples/MultiObjective/MultiObjectiveExample.fs
Flips.Examples/MultipleFoodTrackExample/MultipleFoodTruckExample.fs
Flips.Examples/MultipleFoodTruckSliceMapExample/MultipleFoodTruckSliceMapExample.fs
Flips.Examples/MultipleFoodTruckSliceMapWithUnitsOfMeasureExample/MultipleFoodTruckSliceMapWithUnitsOfMeasureExample.fs
Flips.Examples/Program.fs
Flips.Examples/StocksExample/StocksExample.fs
Flips.Tests/Tests.fs
Flips/Domain.fs
Flips/Flips.fsproj
Flips/Scratchpad.fsx
Flips/Solve.fs
Flips/Types.fs
Flips/UnitsOfMeasure.Domain.fs

- Added ability to add objectives to Model for hierarchical optimization
- Bug fix for `DecisionBuilder<'Measure>` in building a 6 element tuples

Add Multi-Objective Models

---

Flips/Flips.fsproj
Flips/Solve.fs

- Fixed the OPTANO based Solve. Model not correctly translated

Fix optano solve

---

Flips/Flips.fsproj
Flips/Solve.fs

- Removing unnecessary printfn

[81]Fix unnecessary printfn

---

docs/README.md

Nice library! I noticed a few spelling issues and thought fixing them might help.

Few spelling corrections

---

Flips.Tests/Flips.Tests.fsproj
Flips/Domain.fs
Flips/Flips.fsproj
Flips/SliceSet.fs
Flips/Types.fs
Flips/UnitsOfMeasure.Types.fs
RELEASE_NOTES.md
tools/tools.fsproj

* Cleaning up with compiler level set to 5

Cleaning up coding standards

---

Flips/Domain.fs
Flips/ISliceData.fs
Flips/Solve.fs
Flips/UnitsOfMeasure.Domain.fs

Regex find replace again, but this time with feeling.

Fix up malformed returns in xml comments

---

Flips/Solve.fs
RELEASE_NOTES.md
docs/RELEASE_NOTES.md

* Fixed LP File Generation for OPTANO based solvers
* Fixed XML Comments

[93][Fixed[XML Comments and LP File Generation]

---

Flips.Examples/MapSlicingExample/MapSlicingExample.fs
Flips/Flips.fsproj
Flips/ISliceData.fs
Flips/UnitsOfMeasure.Domain.fs
RELEASE_NOTES.md
docs/RELEASE_NOTES.md

Element-wise addition of SliceMaps was incorrectly implemented

[97][Fix][SMap addition fix]

---

Flips.Examples/MultipleFoodTrackExample/MultipleFoodTruckExample.fs
Flips.Examples/MultipleFoodTruckSliceMapExample/MultipleFoodTruckSliceMapExample.fs
Flips.Examples/Program.fs
Flips/Domain.fs
Flips/Solve.fs
docs/slicemaps/README.md
docs/types/README.md

proposal fixes for #104 and #105

Objective value in lp and constraint name in or tools

---

Flips/Flips.fsproj
RELEASE_NOTES.md
docs/RELEASE_NOTES.md

[66][Fix[LP/MPS file generating and added SourceLink]

---

Flips.Examples/BinaryProgrammingExample/BinaryProgrammingExample.fs
Flips.Examples/CoffeeRoastingExample/CoffeeRoastingExample.fs
Flips.Examples/Flips.Examples.fsproj
Flips.Examples/FoodTruckConstraintBuilderExample/FoodTruckConstraintBuilderExample.fs
Flips.Examples/FoodTruckDecisionBuilder/FoodTruckDecisionBuilder.fs
Flips.Examples/FoodTruckExample/FoodTruckExample.fs
Flips.Examples/FoodTruckMapExample/FoodTruckMapExample.fs
Flips.Examples/FoodTruckUnitsOfMeasureExample/FoodTruckUnitsOfMeasureExample.fs
Flips.Examples/MapSlicingExample/MapSlicingExample.fs
Flips.Examples/MultiObjective/MultiObjectiveExample.fs
Flips.Examples/MultipleFoodTrackExample/MultipleFoodTruckExample.fs
Flips.Examples/MultipleFoodTruckSliceMapExample/MultipleFoodTruckSliceMapExample.fs
Flips.Examples/MultipleFoodTruckSliceMapWithUnitsOfMeasureExample/MultipleFoodTruckSliceMapWithUnitsOfMeasureExample.fs
Flips.Examples/SimpleExample/SimpleExample.fs
Flips.Examples/StocksExample/StocksExample.fs
Flips.Solver.CBC/Settings.fs
Flips.Solver.Legacy/Flips.Legacy.Domain.fs
Flips.Solver.Legacy/Flips.Legacy.Types.fs
Flips.Solver.Legacy/Flips.Solver.Legacy.fsproj
Flips/Flips.fsproj
Flips/Types.fs

* Got examples working with the `Flips.Solver.Legacy` backend

Get examples working

---

Flips/Domain.fs
Flips/Flips.fsproj
Flips/ISliceData.fs
Flips/UnitsOfMeasure.Domain.fs

Based on our chat on slack today, here's as much as can be done this very second to make your docs correct.
The main functional issues were around the use of `'` in names, which apparently is a bad thing.
After that there were some parameter mismatch issues, and some escaping issues as well.
I've cleaned up everything I could, but during this actually found two issues with the compilers' parameter-completeness checking for xml docs. I've submitted this issue [here](https://github.com/dotnet/fsharp/issues/10809) for followup.

fix as many invalid docs as possible right now, and turn on docs checking for the future

---

RELEASE_NOTES.md
docs/RELEASE_NOTES.md

Updating release notes

---

Flips/Flips.fsproj

The PR removes duplicate code.  The other occurrence of this code is on old line 14 / new line 13.

removed duplicate setting for GeneratePackageOnBuild

---

Flips/Flips.fsproj
Flips/Solve.fs
Flips/Types.fs
Flips/Utility.fs

I am diving deeper into the code now trying to gain an understanding.  While I am in the neighborhood, I try to simplify the code.
I tried to make many small commits both so that it is easier to statically review and verify that I am preserving behavior and to more easily find a mistake if I made one.
I know that some of the changes I made are subjective, so please feel free change anything back or even ask me to do so.

Code clean up 2020-12-30

---

Flips.sln

Fixing location of `dev-release.yml`

Fixing reference to dev-release.yml

---

Flips/Flips.fsproj

removed unnecessary field

---

Flips/Seq.fs

Reduce surface required to test

Use built-in SequenceEquals

---

docs/README.md

Add some background information on optimisation

---

docs/README.md
docs/RELEASE_NOTES.md

Update documentation of the intro problem
